Output "/Users/kaypark/workspace/colorscheme/fzf-nepes/docs/dark.gif"
Set Width 1280
Set Height 720
Set FontSize 14

Hide
Type "source ~/workspace/colorscheme/fzf-nepes/nepes-dark.sh"
Enter
Sleep 0.5s
Show
Type "find ~/workspace/colorscheme -name '*.py' | fzf --preview 'bat --color=always {}'"
Enter
Sleep 2s
Type "palette"
Sleep 1s
Screenshot "/Users/kaypark/workspace/colorscheme/fzf-nepes/docs/dark.png"
Ctrl+c
